"""Asynchronous Python client for the Tailscale API."""

from .exceptions import (
    TailscaleAuthenticationError,
    TailscaleConnectionError,
    TailscaleError,
    TailscaleNotFoundError,
)
from .models import (
    ClientConnectivity,
    ClientSupports,
    Device,
    DeviceDistro,
    DevicePostureIdentity,
    DevicePostureStatus,
    DeviceRoutes,
    Devices,
    DNSConfiguration,
    DNSConfigurationPreferences,
    DNSNameservers,
    DNSPreferences,
    DNSResolver,
    DNSSearchPaths,
    KeyCapabilities,
    KeyCapabilitiesCreate,
    KeyCapabilitiesDevices,
    Latency,
    PolicyFile,
    PolicyFileValidation,
    PolicyRuleMatch,
    PolicyRulePreview,
    PolicyTestResult,
    TailnetSettings,
    TailscaleKey,
    TailscaleUser,
)
from .storage import TokenStorage
from .tailscale import Tailscale

__all__ = [
    "ClientConnectivity",
    "ClientSupports",
    "DNSConfiguration",
    "DNSConfigurationPreferences",
    "DNSNameservers",
    "DNSPreferences",
    "DNSResolver",
    "DNSSearchPaths",
    "Device",
    "DeviceDistro",
    "DevicePostureIdentity",
    "DevicePostureStatus",
    "DeviceRoutes",
    "Devices",
    "KeyCapabilities",
    "KeyCapabilitiesCreate",
    "KeyCapabilitiesDevices",
    "Latency",
    "PolicyFile",
    "PolicyFileValidation",
    "PolicyRuleMatch",
    "PolicyRulePreview",
    "PolicyTestResult",
    "TailnetSettings",
    "Tailscale",
    "TailscaleAuthenticationError",
    "TailscaleConnectionError",
    "TailscaleError",
    "TailscaleKey",
    "TailscaleNotFoundError",
    "TailscaleUser",
    "TokenStorage",
]
